apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-nodeapp
  namespace: jephilli
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/karthik_jk/test-nodeapp@sha256:aa1009825d9792f03c7fd9febc2f466724b137e16a02b8bb33311e813f2ecb73
        name: container-image
        resources: {}
status: {}
